"""Add payment_method and check_number to Expense model

Revision ID: 7c538ff1d9dc
Revises: bc4afb96b7c9
Create Date: 2024-06-26 22:54:07.133774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c538ff1d9dc'
down_revision = 'bc4afb96b7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('check_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('check_number')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
