"""Add PaymentMethod model and update Expense model

Revision ID: ad291aff9e71
Revises: 7c538ff1d9dc
Create Date: 2024-06-26 23:08:24.700977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad291aff9e71'
down_revision = '7c538ff1d9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'payment_method', ['payment_method_id'], ['id'])
        batch_op.drop_column('payment_method')
        batch_op.drop_column('check_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_method_id')

    op.drop_table('payment_method')
    # ### end Alembic commands ###
