"""Update Expense model with direct credit card info

Revision ID: 2ed17b884cc0
Revises: f16a7e6974a5
Create Date: 2024-06-27 14:34:54.808824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ed17b884cc0'
down_revision = 'f16a7e6974a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_last_four', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('expense_ibfk_1', type_='foreignkey')
        batch_op.drop_column('payment_method_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expense_ibfk_1', 'payment_method', ['payment_method_id'], ['id'])
        batch_op.drop_column('card_type')
        batch_op.drop_column('card_last_four')

    # ### end Alembic commands ###
