"""Add rent_due_date to Unit model

Revision ID: 60db00669379
Revises: f1672e856f9b
Create Date: 2024-06-29 10:25:37.183631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60db00669379'
down_revision = 'f1672e856f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_payment')
    # ### end Alembic commands ###
