"""Add Payable model

Revision ID: b7fba27a4c79
Revises: d112be16f082
Create Date: 2024-06-28 22:13:46.150280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fba27a4c79'
down_revision = 'd112be16f082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('payment_method_type', sa.String(length=20), nullable=False),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payable')
    # ### end Alembic commands ###
