"""Remove payment method fields from Payable model

Revision ID: f1672e856f9b
Revises: b7fba27a4c79
Create Date: 2024-06-28 23:15:01.266885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1672e856f9b'
down_revision = 'b7fba27a4c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payable', schema=None) as batch_op:
        batch_op.drop_column('card_type')
        batch_op.drop_column('payment_method_type')
        batch_op.drop_column('card_last_four')
        batch_op.drop_column('check_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('card_last_four', mysql.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('payment_method_type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_type', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
