"""Update Expense model with new payment method fields

Revision ID: f16a7e6974a5
Revises: 8a50d5cf6e9e
Create Date: 2024-06-26 23:29:55.623143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f16a7e6974a5'
down_revision = '8a50d5cf6e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('check_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('payment_method_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('payment_method_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('check_number')
        batch_op.drop_column('payment_method_type')

    # ### end Alembic commands ###
